# Generated by Django 5.0.3 on 2024-03-28 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConversaitonMessage',
            new_name='ConversationMessage',
        ),
    ]
